### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' 

### ISSUE THREAD

**Issue by czalt1028** [bubbliiiing/mobilenet-yolov4-lite-keras#1]
Traceback (most recent call last): File "D:/AI/projects/mobilenet-yolov4-lite-keras-main/mobilenet-yolov4-lite-keras-main/train.py", line 257, in <module> model_body.load_weights(weights_path, by_name=True, skip_mismatch=True) File "D:\AI\anaconda3-5.3.1\envs\yolov4\lib\site-packages\keras\engine\topology.py", line 2653, in load_weights reshape=reshape) File "D:\AI\anaconda3-5.3.1\envs\yolov4\lib\site-packages\keras\engine\topology.py", line 3407, in load_weights_from_hdf5_group_by_name original_keras_version = f.attrs['keras_version'].decode('utf8') AttributeError: 'str' object has no attribute 'decode' 训练时报错，怎能解决啊？

**Comment by bubbliiiing** [comment]
环境配置的博客

**Comment by czalt1028** [comment]
> 环境配置的博客

多谢！可以了！PS：希望大佬能加入tensorboard的代码，可视化显示训练时的各种指标！

**Comment by bubbliiiing** [comment]
ps前再看看代码
